### ISSUE TITLE
Warning in com_sendinblue file subscription_form.php

### ISSUE THREAD

**Issue by AlainRnet** [sendinblue/joomla-plugin#1]
When I create or edit a Subscription form in the SendInBlue component, I have following PHP warning :
Warning: Declaration of SendinblueModelSubscription_form::validate($form, $data) should be compatible with Joomla\CMS\MVC\Model\FormModel::validate($form, $data, $group = NULL) in /administrator/components/com_sendinblue/models/subscription_form.php on line 21

I think line 56 in /administrator/components/com_sendinblue/models/subscription_form.php file should be :
public function validate($form, $data, $group = NULL)

**Comment by branislavgligorov** [comment]
Hi, thanks for contribution. This is resolved in new version 1.0.3.
