### ISSUE TITLE
Mails transactionnels

### ISSUE THREAD

**Issue by sara880** [sendinblue/joomla-plugin#2]
Bonjour,

Nous gérons les mails transactionnels via Mailjet actuellement. Nous avons déjà un compte Sendinblue et souhaitons traiter les mails transactionnels via Sendinblue, comment devons-nous procéder ?

Dans l'attente,

Sara

**Comment by branislavgligorov** [comment]
Bonjour Sara,

Il faut simplement vous assurer que la plateforme transactionnelle est
activée sur votre compte Sendinblue.
Pour la mise en place des emails transactionnels via le module Joomla,
suivez ce tutoriel
<https://help.sendinblue.com/hc/fr/articles/360002682500-Joomla-4-Envoyer-des-emails-transactionnels-avec-SendinBlue>
.
Si vous avez des questions complémentaires, n'hésitez pas à contacter notre
support pour toute question à l'adresse support@sendinblue.com.

Cordialement
