### ISSUE TITLE
Envoi de SMS 

### ISSUE THREAD

**Issue by Mathieu44** [sendinblue/joomla-plugin#3]
Bonjour,

Est ce que le module Sendinblue de Joomla permet également de gérer et d'envoyer des campagnes SMS ?

Merci

**Comment by branislavgligorov** [comment]
Bonjour,
Merci de l'intérêt porté à notre module.
Pour le moment, celui-ci ne permet pas la gestion et l'envoi des campagnes SMS.
Il faudra passer directement sur la plateforme Sendinblue.
Votre demande a été remontée à notre équipe Produit pour de futures améliorations !

Cordialement
