### ISSUE TITLE
the installation does not work

### ISSUE THREAD

**Issue by Domo222** [sendinblue/joomla-plugin#4]
unfortunately the installation does not work. The following error occurs. :Plese help me.
Dominik

Warnung
JInstaller: :Install: SQL-Fehler Index column size too large. The maximum column size is 767 bytes.
Erweiterung „Installieren“: SQL Fehler beim Ausführen der Abfrage: „DB-Funktion mit Fehlercode 1709 fehlgeschlagen!
Index column size too large. The maximum column size is 767 bytes.
SQL =

CREATE TABLE IF NOT EXISTS `#__sendinblue_subscription_data` (	`id` INT(11) NOT NULL AUTO_INCREMENT,	`asset_id` INT(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',	`confirmationtype` TINYINT(1) NULL DEFAULT 0,	`email` VARCHAR(255) NOT NULL DEFAULT '',	`subscriptionformid` INT NOT NULL DEFAULT 0,	`token` TEXT NULL,	`params` text NOT NULL DEFAULT '',	`published` TINYINT(3) NOT NULL DEFAULT 1,	`created_by` INT(10) unsigned NOT NULL DEFAULT 0,	`modified_by` INT(10) unsigned NOT NULL DEFAULT 0,	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',	`checked_out` int(11) unsigned NOT NULL DEFAULT 0,	`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',	`version` INT(10) unsigned NOT NULL DEFAULT 1,	`hits` INT(10) unsigned NOT NULL DEFAULT 0,	`access` INT(10) unsigned NOT NULL DEFAULT 0,	`ordering` INT(11) NOT NULL DEFAULT 0,	PRIMARY KEY  (`id`),	KEY `idx_access` (`access`),	KEY `idx_checkout` (`checked_out`),	KEY `idx_createdby` (`created_by`),	KEY `idx_modifiedby` (`modified_by`),	KEY `idx_state` (`published`),	KEY `idx_email` (`email`)) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_general_ci;

“
Paket Installieren: Bei der Installation der Erweiterung trat ein Fehler auf: com_sendinblue_v1_0_6.zip
×
Fehler
Fehler bei der Paket-Installation.

**Comment by branislavgligorov** [comment]
Hi Domink did you check versions compatibility?

**Comment by Domo222** [comment]
I am not sure, which infos you need.

I installend this Version:
1.0.6 (last updated on 03 June 2020)
License GPLv2 or later
Added On
23 January 2019
Compatible Versions
3.x
Component Module Plugin 
 Install    Directory Listing    Developer Website
SendinBlue (By Branislav)


PHP-Version | 7.3.22
Joomla!-Version | Joomla!   3.9.21 Stable [ Amani ] 25-August-2020 15:00 GMT
Joomla!-Plattform-Version | Joomla   Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

Thank you

**Comment by sarandos** [comment]
Hi, i have the same problem!!

**Comment by branislavgligorov** [comment]
Hi Dominik, can you please check which version of MySQL database you are using? You can read it easily in Joomla System Information. 
Sarandos it will be nice if you can also submit the same info.
Thanks

**Comment by Domo222** [comment]
PHP-Version | 7.3.22
Dominik

**Comment by sarandos** [comment]
MySql  5.5.5-10.1.46-MariaDB-cll-lve 
Php
 7.3.22

**Comment by branislavgligorov** [comment]
Hi, please try with new version 1.0.7 it should resolve this problem. 
New version is available on Joomla! Extensions Directory or it could be installed directly from Joomla web installer.
Please let me know if you managed to install it properly.

**Comment by sarandos** [comment]
Hi, it is ok now Thank you very much!!!

**Comment by Domo222** [comment]
no error during installation.
Thank you very much!
dominik
