### ISSUE TITLE
Less E-mail campaign recipients

### ISSUE THREAD

**Issue by Markableuae** [sendinblue/joomla-plugin#6]
Hello **Sendinblue Team,**

Greetings!

This is Glaze from **Markable UAE**.

We are sending this e-mail to help us solve our issues regarding the following concerns below.

1. We gathered **13,144 contacts** how come that we only have **3,000+ contact recipients** in our email campaigns?
2. How can we resend again to the **remaining 10,000+ contacts** for our previous e-mail campaigns.

![image](https://user-images.githubusercontent.com/72190269/94782336-2302b300-03dc-11eb-83f8-488851c86433.png)
![image](https://user-images.githubusercontent.com/72190269/94782277-0e261f80-03dc-11eb-920f-6bfdb091b655.png)

Hope to hear back from your good team.

Thank you!

Best Regards,
Glaze

**Comment by branislavgligorov** [comment]
Hi, please for this question try to contact support directly at https://help.sendinblue.com/hc/en-us
