### ISSUE TITLE
I want to add styles to the basic form

### ISSUE THREAD

**Issue by florbona** [sendinblue/joomla-plugin#8]
do you have an example of this?

**Comment by imtoofat145** [comment]
Bump ..do you have an example of this? I've applied whatever constitutes standard CSS to no avail. The couple of simple pointers would be helpful for example how do you centre justify.. Everything is left justified by default and nothing seems to affect that. Equally how can i override the current submit button is black. Thanks in advance for any guidance

**Comment by branislavgligorov** [comment]
Hi, basically the idea is to take styles from template. Beside that you can completely restyle the form by adding your own CSS classes and styling. Every single field in form has three options for adding custom styling: Block class - additional class for label and field together, Block Style - custom CSS rules for label and field together and Block control class - additional class only for entry field. All this fields are accessibly while editing form fileds. 
Additionally the form is wrapped with id="sendinblueform-form" so for some advanced styling the rules like 
#sendinblueform-form button {} should make any changes easy.

**Comment by imtoofat145** [comment]
@branislavgligorov thanks for the detailed reply
